apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
  namespace: sit
spec:
  selector:
    matchLabels:
      app: stockmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
        - name: stockmanager
          image: ecrregis/java:latest
          ports:
            - containerPort: 8030
          livenessProbe:
            httpGet:
              path: /stocks
              port: 8030
            initialDelaySeconds: 30
            timeoutSeconds: 1
