apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  type: LoadBalancer
  selector:
    app: stockmanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8030
